apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: auth-policy
spec:
  targets:
  - name: api
  origins:
  - jwt:
      issuer: "https://dev-1bi5o566.auth0.com/"
      jwksUri: "https://dev-1bi5o566.auth0.com/.well-known/jwks.json"
  principalBinding: USE_ORIGIN


